CREATE TABLE replenishment_items (
    location_id varchar(60),
    location_name varchar(60),
    inv_mast_uid varchar(60),
    item_id varchar(60),
    item_desc varchar(60),
    on_vendor_price_book varchar(60),
    product_type varchar(60),
    primary_supplier_id varchar(60),
    supplier_name varchar(60),
    replenishment_method varchar(60),
    replenishment_location varchar(60),
    inv_min integer,
    inv_max integer,
    stockable varchar(60),
    sellable varchar(60),
    buyable varchar(60),
    qty_on_hand integer,
    track_bins varchar(60),
    primary_bin varchar(60),
    repl_loc_review varchar(60),
    repl_meth_review varchar(60),
    track_bin_review varchar(60),
    discrepancy_type varchar(60)
);